import test from 'node:test';
import assert from 'node:assert/strict';
import {Demolition,LEVELS,TOOLS,freshProfile,sanitizeProfile,buyUpgrade,award,initPhysics,type Tool} from '../src/simulation.ts';
await initPhysics();
function advance(g:Demolition,seconds:number){for(let i=0;i<Math.ceil(seconds*60);i++){g.tick(1/60);g.events=[];}}
function fire(g:Demolition,id:number,tool:Tool='breaker'){assert.ok(g.strike(id,tool));advance(g,TOOLS[tool].cooldown+.03);}
function precisionClear(g:Demolition){for(const n of g.modules.filter(n=>n.floor===0)){while(n.state==='standing'&&g.phase==='active'){if(g.energy<1)break;fire(g,n.id);}}advance(g,7);}
test('a broken support releases its own upper floors and leaves adjacent columns intact',()=>{const g=new Demolition(1);const support=g.modules.find(n=>n.floor===0)!;fire(g,support.id);assert.equal(support.state,'standing');fire(g,support.id);assert.equal(support.state,'rubble');assert.ok(g.modules.filter(n=>n.col===support.col&&n.row===support.row&&n.floor>0).every(n=>n.state==='falling'||n.state==='rubble'));assert.ok(g.modules.some(n=>n.col!==support.col&&n.state==='standing'));assert.equal(g.progress,1/4);assert.ok(g.maxChain>=3);advance(g,3);assert.ok(g.pieces.length>=12);g.dispose();});
test('energy, cooldowns and tool unlocks cannot be bypassed',()=>{const g=new Demolition(0);assert.equal(g.strike(999,'breaker'),false);assert.equal(g.strike(1,'ball'),false);assert.equal(g.energy,12);assert.ok(g.strike(1,'breaker'));assert.equal(g.energy,11);assert.equal(g.strike(1,'breaker'),false);advance(g,1);g.energy=0;assert.equal(g.strike(1,'breaker'),false);advance(g,1);assert.equal(g.phase,'failed');g.dispose();});
test('the last available hit can complete a site even when energy reaches zero',()=>{const g=new Demolition(0);for(const n of g.modules.filter(n=>n.floor===0).slice(0,-1)){fire(g,n.id);fire(g,n.id);}const last=g.modules.find(n=>n.floor===0&&n.state==='standing')!;fire(g,last.id);g.energy=1;fire(g,last.id);advance(g,6);assert.equal(g.phase,'won');g.dispose();});
test('pause freezes a pending explosion, physics and the job timer',()=>{const p=freshProfile();p.unlocked=4;const g=new Demolition(4,p);assert.ok(g.strike(1,'blast'));g.paused=true;const before=JSON.stringify(g.snapshot());advance(g,4);assert.equal(JSON.stringify(g.snapshot()),before);assert.ok(g.pending);g.paused=false;advance(g,1.5);assert.equal(g.pending,null);assert.ok(g.modules.some(n=>n.hp<n.maxHp));g.dispose();});
test('ball and dynamite affect multiple nearby modules with their advertised energy costs',()=>{const p=freshProfile();p.unlocked=8;p.upgrades.power=3;for(const tool of ['ball','blast'] as Tool[]){const g=new Demolition(2,p);fire(g,2,tool);assert.equal(g.energy,g.config.energy-TOOLS[tool].cost);assert.ok(g.modules.filter(n=>n.hp<n.maxHp).length>=2);assert.ok(g.progress>0);g.dispose();}});
test('wide blasts near the protected neighbor can fail the job',()=>{const p=freshProfile();p.unlocked=8;p.upgrades.reach=3;const g=new Demolition(7,p);const right=g.modules.filter(n=>n.floor===0&&n.col===g.config.cols-1);for(const n of right){if(g.phase==='active')fire(g,n.id,'blast');}assert.ok(g.neighbor<75,`${g.neighbor}`);assert.equal(g.phase,'failed');g.dispose();});
test('upgrades spend funds once, stop at level three and preserve valid saved data',()=>{const p=freshProfile();assert.equal(buyUpgrade(p,'power'),false);p.coins=1000;assert.ok(buyUpgrade(p,'power'));assert.equal(p.coins,880);assert.ok(buyUpgrade(p,'power'));assert.ok(buyUpgrade(p,'power'));assert.equal(buyUpgrade(p,'power'),false);assert.equal(p.upgrades.power,3);assert.deepEqual(sanitizeProfile(p),p);assert.equal(sanitizeProfile({coins:-5,unlocked:100,stars:[8],upgrades:{power:99}}).upgrades.power,3);assert.equal(sanitizeProfile(null).coins,0);});
test('all nine sites are completable in sequence using only earned upgrades',()=>{const p=freshProfile(),results=[];for(let level=0;level<9;level++){while(buyUpgrade(p,'power')){}const g=new Demolition(level,p);precisionClear(g);results.push({site:level+1,phase:g.phase,energy:g.energy,neighbor:+g.neighbor.toFixed(1),stars:g.stars,power:p.upgrades.power});assert.equal(g.phase,'won',JSON.stringify(g.snapshot()));assert.ok(g.stars>=1);award(p,level,g.stars);assert.ok(p.unlocked>=Math.min(level+1,8));g.dispose();}console.log('Career check:',JSON.stringify(results));});
test('job pay rewards a first clear more than a replay and never erases best stars',()=>{const p=freshProfile();const first=award(p,0,3),replay=award(p,0,1);assert.ok(first>replay);assert.equal(p.stars[0],3);const before=p.coins;assert.equal(award(p,1,0),0);assert.equal(p.coins,before);assert.equal(p.unlocked,1);});
test('site size and support strength increase, and the timer waits for the first hit',()=>{for(let i=1;i<9;i++){assert.ok(LEVELS[i].hp>LEVELS[i-1].hp);assert.ok(LEVELS[i].cols*LEVELS[i].floors>=LEVELS[i-1].cols*LEVELS[i-1].floors);}const g=new Demolition(0);advance(g,20);assert.equal(g.elapsed,0);assert.equal(g.progress,0);g.dispose();});
