import './style.css';
import {Demolition,initPhysics,LEVELS,TOOLS,freshProfile,sanitizeProfile,buyUpgrade,award,UPGRADE_COSTS,type Profile,type Tool,type Upgrade} from './simulation';
import {Scene} from './world';
import {Sound} from './audio';
const svg=(s:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${s}</svg>`;
const icons={breaker:svg('<path d="m14 3 7 7-4 4-7-7zM12 10l-7 7m-2 4 5-2-3-3-2 5"/>'),ball:svg('<path d="M12 2v9m-2-7h4m-4 4h4"/><circle cx="12" cy="17" r="5"/>'),blast:svg('<rect x="4" y="9" width="5" height="12" rx="2"/><rect x="10" y="7" width="5" height="14" rx="2"/><rect x="16" y="9" width="4" height="12" rx="2"/><path d="M12 7V4q0-3 5-2M3 14h18"/>'),coins:svg('<circle cx="12" cy="12" r="9"/><path d="M15 8h-5a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H9m3-10v12"/>'),arrow:svg('<path d="M4 12h16m-6-6 6 6-6 6"/>'),power:svg('<path d="m13 2-9 12h7l-1 8 10-13h-7l1-7"/>'),reach:svg('<path d="M3 8V3h5m8 0h5v5M3 16v5h5m8 0h5v-5M8 12h8m-4-4v8"/>'),salvage:svg('<path d="M3 8h12v10H3zm12 3h4l3 4v3h-7"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>'),sound:svg('<path d="m11 4-6 5H2v6h3l6 5V4m5 4a6 6 0 0 1 0 8m3-12a11 11 0 0 1 0 16"/>')};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let profile:Profile=freshProfile();try{profile=sanitizeProfile(JSON.parse(localStorage.getItem('rubble-club-save')||'null'));}catch{}
const sound=new Sound();try{sound.enabled=localStorage.getItem('rubble-club-sound')!=='false';}catch{}
let game:Demolition,world:Scene,tool:Tool='breaker',modal='',toastTime=0,resultSaved=false,earned=0,stopTime=0,hoverId=-1;
const root=document.querySelector<HTMLDivElement>('#app')!;
root.innerHTML=`<main class="shell"><div id="world"></div>
<header><a class="brand" href="#"><span class="brand-mark">${icons.breaker}</span><span>Rubble Club<small>GOOD DAYS. GREAT DEMOLITIONS.</small></span></a><div class="header-center"><span class="live-dot"></span>CREW ON SITE</div><div class="header-tools"><button id="sites">Sites <span>↗</span></button><button id="workshop">Workshop ${icons.power}</button><button id="sound" class="icon-button" aria-label="Mute sound">${icons.sound}</button><button id="help" class="icon-button" aria-label="How to play">?</button></div></header>
<section class="story"><div class="eyebrow">A LITTLE DESTRUCTION. A LOT OF JOY.</div><h1>Small crew.<br><span>Big crunch.</span></h1><div class="site-line"><b id="site-number">01</b><div><small id="area"></small><h2 id="site-name"></h2></div></div><p id="brief"></p><div class="tiny-note"><span>↘</span> Start with the<br>striped supports.</div></section>
<aside class="job-card"><div class="job-card-top"><span>TODAY’S JOB</span><button id="pause" aria-label="Pause game">Ⅱ</button></div><div class="progress-row"><strong id="clear">0<span>%</span></strong><span>CLEAR THE<br>WHOLE BUILDING</span></div><div class="progress-track"><i id="progress"></i></div><div class="job-stats"><div><span>ENERGY</span><strong id="energy">12 <small>/ 12</small></strong></div><div><span>TIME</span><strong id="time">0.0<small>s</small></strong></div></div><div id="neighbor" class="neighbor" hidden><span>♥ Neighbor safety</span><b id="neighbor-hp">100%</b></div><small id="goal-note"></small></aside>
<div class="wallet">${icons.coins}<b id="coins">0</b><span>CREW FUNDS</span></div>
<div id="target-hint" class="target-hint" hidden><span id="target-label"></span><div><i id="target-hp"></i></div><small id="target-tip"></small></div>
<div id="toast" role="status"></div><div id="combo" class="combo" hidden><strong id="combo-value"></strong><span>CHAIN REACTION!</span></div>
<div class="view-controls"><button id="rotate-left" aria-label="Rotate view left">↶</button><span>DRAG TO ROTATE</span><button id="rotate-right" aria-label="Rotate view right">↷</button></div>
<section id="toolbox" class="toolbox"><div class="toolbox-label"><span>01 / CHOOSE YOUR TOOL</span><b>Tap a support.<br>Let gravity do the rest.</b></div><div class="tool-list">${(Object.keys(TOOLS) as Tool[]).map((t,i)=>`<button class="tool-card" data-tool="${t}"><span class="tool-number">0${i+1}</span><span class="tool-icon">${icons[t]}</span><span class="tool-copy"><b>${TOOLS[t].name}</b><small id="tool-info-${t}"></small></span><span class="tool-check">✓</span></button>`).join('')}</div><div class="tool-status"><span id="ready-dot"></span><b id="ready">READY</b><small id="cost">1 ENERGY / HIT</small></div></section>
<div id="cleanup" class="cleanup" hidden><span class="eyebrow">THAT WAS A GOOD CRUNCH.</span><h2>We’ll take it from here.</h2><p>Your little truck is collecting the rubble.</p><span class="loader-dots">● ● ●</span></div>
<footer>BUILT TO FALL APART. <span>✦</span> RUBBLE CLUB</footer>
<div id="modal" class="modal" hidden><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button id="modal-close" class="close" aria-label="Close dialog">×</button><span id="modal-eyebrow" class="eyebrow"></span><h2 id="modal-title"></h2><div id="modal-body"></div><button id="modal-action" class="primary"></button><button id="modal-secondary" class="secondary" hidden></button></section></div>
<div id="loading" class="loading"><div>${icons.breaker}</div><h2>A little crew is on its way.</h2><p>Setting up your colorful demolition site…</p></div></main>`;
function save(){try{localStorage.setItem('rubble-club-save',JSON.stringify(profile));}catch{}}
function toast(message:string){$('toast').textContent=message;$('toast').classList.add('show');toastTime=3;}
function choose(t:Tool){if(!game.canUse(t)){toast(`Finish site ${TOOLS[t].unlock} to unlock ${TOOLS[t].name.toLowerCase()}.`);return;}tool=t;world.tool=t;sound.unlock();sound.play('select');sync();}
function sync(){if(!game)return;document.querySelector<HTMLElement>('.shell')!.dataset.phase=game.phase;document.querySelector<HTMLElement>('.shell')!.dataset.started=String(game.hits>0);
 $('site-number').textContent=String(game.level+1).padStart(2,'0');$('area').textContent=game.config.area;$('site-name').textContent=game.config.name;$('brief').textContent=game.config.brief;
 $('clear').innerHTML=`${Math.round(game.progress*100)}<span>%</span>`;$('progress').style.width=`${game.progress*100}%`;$('energy').innerHTML=`${game.energy} <small>/ ${game.config.energy}</small>`;$('time').innerHTML=`${game.elapsed.toFixed(1)}<small>s</small>`;$('coins').textContent=profile.coins.toLocaleString();$('goal-note').textContent=`3 STARS: ≤ ${game.config.par}s · SAVE ${Math.floor(game.config.energy*.15)} ENERGY`;
 $('neighbor').hidden=!game.config.protected;$('neighbor-hp').textContent=`${Math.round(game.neighbor)}%`;$('neighbor').classList.toggle('warning',game.neighbor<90);
 document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>{const t=b.dataset.tool as Tool,unlocked=game.canUse(t);b.classList.toggle('selected',tool===t);b.classList.toggle('locked',!unlocked);b.setAttribute('aria-pressed',String(tool===t));b.setAttribute('aria-label',`${TOOLS[t].name}, ${unlocked?TOOLS[t].cost+' energy':'unlocks after site '+TOOLS[t].unlock}`);$('tool-info-'+t).textContent=unlocked?`${TOOLS[t].cost} ENERGY · ${t==='breaker'?'PRECISE':t==='ball'?'WIDE SWING':'BIG BOOM'}`:`FINISH SITE ${TOOLS[t].unlock} TO UNLOCK`;});
 $('ready').textContent=game.cooldown>0?'WORKING':game.energy<TOOLS[tool].cost?'LOW ENERGY':'READY';$('ready-dot').classList.toggle('busy',game.cooldown>0);$('cost').textContent=`${TOOLS[tool].cost} ENERGY / HIT`;
 $('toolbox').hidden=game.phase==='cleanup'||game.phase==='won';$('cleanup').hidden=game.phase!=='cleanup';
 const n=game.modules.find(n=>n.id===hoverId&&n.state==='standing');$('target-hint').hidden=!n||game.phase!=='active'||!!modal;if(n){$('target-label').textContent=n.floor===0?(n.reinforced?'REINFORCED SUPPORT':'LOAD-BEARING SUPPORT'):`FLOOR ${n.floor+1}`;$('target-hp').style.width=`${n.hp/n.maxHp*100}%`;$('target-tip').textContent=`${Math.ceil(n.hp)} / ${Math.ceil(n.maxHp)} HP · ${n.floor===0?'BRING THE STACK DOWN':'AIM LOWER FOR A CHAIN'}`;}
}
function reset(level:number){game?.dispose();game=new Demolition(level,profile);world?.reset();tool='breaker';hoverId=-1;resultSaved=false;earned=0;modal='';stopTime=0;$('modal').hidden=true;sync();}
function close(){if(game.phase==='won'||game.phase==='failed'){openModal('result');return;}modal='';$('modal').hidden=true;game.paused=false;sync();}
const upgradeCopy={power:{title:'More muscle',text:'22% more damage per level. Tough supports need fewer hits.'},reach:{title:'Wider swing',text:'Larger ball and dynamite impact areas. Watch nearby buildings.'},salvage:{title:'Happy hauler',text:'15% more job pay per level, plus faster rubble collection.'}};
function openModal(kind:string){modal=kind;game.paused=true;hoverId=-1;world.targetId=-1;$('modal').hidden=false;$('modal-close').hidden=kind==='result';$('modal-secondary').hidden=true;$('modal-eyebrow').textContent=kind==='sites'?'NINE LITTLE DEMOLITIONS':kind==='workshop'?'SMALL UPGRADES. BIG DIFFERENCE.':kind==='help'?'WELCOME TO THE CLUB':kind==='result'?(game.phase==='won'?'ANOTHER BLOCK, BEAUTIFULLY CLEARED':'A LITTLE DO-OVER'):'TAKE A BREATHER';
 $('modal-title').textContent=kind==='sites'?'Pick your next crunch.':kind==='workshop'?'The crew workshop.':kind==='help'?'A good day to break things.':kind==='result'?(game.phase==='won'?'That’s a wrap.':'Let’s rethink that one.'):'Tools down for a moment.';
 if(kind==='sites'){$('modal-body').innerHTML=`<div class="site-grid">${LEVELS.map((l,i)=>`<button data-site="${i}" class="site-card theme-${l.theme}" ${i>profile.unlocked?'disabled':''}><small>SITE ${String(i+1).padStart(2,'0')} · ${l.floors} FLOORS</small><b>${l.name}</b><span>${i>profile.unlocked?'LOCKED':'★'.repeat(profile.stars[i])+'☆'.repeat(3-profile.stars[i])}</span></button>`).join('')}</div><p>Clear one site to unlock the next. Replay completed jobs for extra crew funds.</p>`;$('modal-action').textContent='Back to the site';}
 else if(kind==='workshop'){$('modal-body').innerHTML=`<div class="workshop-funds">${icons.coins}<b>${profile.coins}</b><span>crew funds</span></div><div class="upgrades">${(Object.keys(upgradeCopy) as Upgrade[]).map(k=>{const rank=profile.upgrades[k],cost=UPGRADE_COSTS[k][rank];return `<article><span class="upgrade-icon">${icons[k]}</span><div><b>${upgradeCopy[k].title}</b><small>LEVEL ${rank} / 3</small><p>${upgradeCopy[k].text}</p></div><button data-upgrade="${k}" ${rank>=3||profile.coins<cost?'disabled':''}>${rank>=3?'MAXED':cost+' ◉'}</button></article>`;}).join('')}</div><p>Upgrades stay with your crew. Failed jobs cost no coins to retry.</p>`;$('modal-action').textContent='Back to work';}
 else if(kind==='help'){$('modal-body').innerHTML=`<ol class="help-list"><li><b>Start at the striped supports</b><span>Tap a yellow ground-floor support to hit it. Break it and every floor above it falls. Cracks show damage.</span></li><li><b>Choose your tool</b><span>Breaker: precise, 1 energy. Ball: wider hit, 3 energy, unlocks after site 2. Dynamite: 4 energy, unlocks after site 4.</span></li><li><b>Look around the building</b><span>Drag the scene or use ↶ / ↷ to rotate. Reach the back row and plan a bigger chain reaction.</span></li><li><b>Protect the neighbor</b><span>On marked sites, keep the pink shop at 75% or more. Wide blasts and flying rubble can damage it.</span></li><li><b>Clear, collect, upgrade</b><span>Clear the whole building before energy runs out. Keep the neighbor at 95% for two stars; also meet time and energy targets for three. P pauses; 1 / 2 / 3 choose tools.</span></li></ol>`;$('modal-action').textContent='Let’s make a little mess';}
 else if(kind==='result'){$('modal-body').innerHTML=game.phase==='won'?`<div class="stars">${[0,1,2].map(i=>`<span class="${game.stars>i?'earned':''}" style="--i:${i}">★</span>`).join('')}</div><div class="receipt"><div><span>Site cleared</span><b>${game.config.name}</b></div><div><span>Time / target</span><b>${game.elapsed.toFixed(1)} / ${game.config.par}s</b></div><div><span>Energy saved</span><b>${game.energy} / ${game.config.energy}</b></div>${game.config.protected?`<div><span>Neighbor safety</span><b>${Math.round(game.neighbor)}%</b></div>`:''}<div class="total"><span>CREW PAY</span><b>+${earned} ◉</b></div></div><p>${game.level===1?'Wrecking ball unlocked! Your next job just got more interesting.':game.level===3?'Dynamite unlocked! Save your big boom for the right spot.':game.level===8?'All nine sites cleared. Your little crew made a big difference.':'Visit the workshop for more power, wider swings and better pay.'}</p>`:`<div class="fail-icon">${icons.breaker}</div><p>${game.neighbor<75?'The neighbor took too much damage. Use the precise breaker near the pink shop.':'Out of energy. Target the bottom supports for chain reactions, or upgrade your power in the workshop.'}</p><div class="receipt"><div><span>Building cleared</span><b>${Math.round(game.progress*100)}%</b></div><div><span>Neighbor safety</span><b>${Math.round(game.neighbor)}%</b></div></div>`;$('modal-action').textContent=game.phase==='won'&&game.level<8?'Next site →':'Try this site again';$('modal-secondary').hidden=false;$('modal-secondary').textContent='Visit workshop';}
 else{$('modal-body').innerHTML='<p>Your crew and every little piece of rubble are on pause.</p>';$('modal-action').textContent='Keep crunching';$('modal-secondary').hidden=false;$('modal-secondary').textContent='Restart this site';}
 $('modal-action').focus();sync();
}
function perform(id:number){if(modal||game.phase!=='active')return;sound.unlock();if(game.strike(id,tool)){hoverId=id;sync();}else if(game.energy<TOOLS[tool].cost)toast('Not enough energy for this tool. Try the breaker.');}
$('sites').onclick=()=>openModal('sites');$('workshop').onclick=()=>openModal('workshop');$('help').onclick=()=>openModal('help');$('pause').onclick=()=>openModal('pause');$('modal-close').onclick=close;
$('sound').onclick=()=>{sound.unlock();sound.enabled=!sound.enabled;try{localStorage.setItem('rubble-club-sound',String(sound.enabled));}catch{}$('sound').classList.toggle('muted',!sound.enabled);$('sound').setAttribute('aria-label',sound.enabled?'Mute sound':'Enable sound');};
$('modal-action').onclick=()=>{sound.unlock();if(modal==='result'){reset(game.phase==='won'&&game.level<8?game.level+1:game.level);}else close();};
$('modal-secondary').onclick=()=>{if(modal==='result')openModal('workshop');else reset(game.level);};
$('modal-body').onclick=e=>{const el=e.target as HTMLElement,site=el.closest<HTMLButtonElement>('[data-site]'),up=el.closest<HTMLButtonElement>('[data-upgrade]');if(site&&!site.disabled)reset(Number(site.dataset.site));if(up&&!up.disabled&&buyUpgrade(profile,up.dataset.upgrade as Upgrade)){save();sound.unlock();sound.play('upgrade');openModal('workshop');}};
document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>choose(b.dataset.tool as Tool));
$('rotate-left').onclick=()=>{if(!modal)world.orbit(-Math.PI/4);};$('rotate-right').onclick=()=>{if(!modal)world.orbit(Math.PI/4);};
window.addEventListener('keydown',e=>{if(!game||e.repeat)return;if(e.code==='KeyP'||e.code==='Escape'){if(modal&&modal!=='result')close();else if(!modal)openModal('pause');return;}if(modal)return;if(e.code==='Digit1')choose('breaker');if(e.code==='Digit2')choose('ball');if(e.code==='Digit3')choose('blast');if(e.code==='ArrowLeft'){world.orbit(-Math.PI/4);e.preventDefault();}if(e.code==='ArrowRight'){world.orbit(Math.PI/4);e.preventDefault();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.phase==='active'&&!modal)openModal('pause');});
async function boot(){try{await initPhysics();game=new Demolition(profile.unlocked,profile);world=new Scene($('world'));$('loading').hidden=true;$('sound').classList.toggle('muted',!sound.enabled);$('sound').setAttribute('aria-label',sound.enabled?'Mute sound':'Enable sound');
 const canvas=world.renderer.domElement;let pointer:{id:number;x:number;y:number;lastX:number;dragged:boolean}|null=null;
 canvas.addEventListener('pointerdown',e=>{if(modal)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,dragged:false};canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(modal)return;if(pointer){if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>7)pointer.dragged=true;if(pointer.dragged)world.orbit(-(e.clientX-pointer.lastX)*.008);pointer.lastX=e.clientX;}hoverId=world.pick(e.clientX,e.clientY,game);world.targetId=hoverId;});
 canvas.addEventListener('pointerup',e=>{if(pointer&&!pointer.dragged)perform(world.pick(e.clientX,e.clientY,game));pointer=null;});canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('pointerleave',()=>{if(!pointer){hoverId=-1;world.targetId=-1;}});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();game.paused=true;toast('Graphics connection lost. Refresh to restart this site.');});
 let last=performance.now(),acc=0,ui=0,comboTime=0;
 function frame(now:number){const dt=Math.min(.05,(now-last)/1000);last=now;if(stopTime>0)stopTime=Math.max(0,stopTime-dt);else{acc+=dt;while(acc>=1/60){game.tick(1/60);acc-=1/60;}}
  for(const ev of game.events){world.event(ev,game);sound.play(ev.type);if(ev.type==='hit'){stopTime=world.reduced?0:.045;if(game.chain>=2){$('combo-value').textContent=`${game.chain}×`;$('combo').hidden=false;comboTime=1.5;}}if(ev.type==='danger'&&(ev.amount||0)>1)toast('Careful! Keep the neighbor above 75%.');}
  game.events=[];
  if((game.phase==='won'||game.phase==='failed')&&!resultSaved){resultSaved=true;if(game.phase==='won'){earned=award(profile,game.level,game.stars);save();}openModal('result');}
  world.update(game,game.paused&&game.phase!=='won'||stopTime>0?0:dt,game.paused?1:acc*60);
  if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('show');}if(comboTime>0){comboTime-=dt;if(comboTime<=0)$('combo').hidden=true;}ui+=dt;if(ui>.1){sync();ui=0;}requestAnimationFrame(frame);
 }
 sync();requestAnimationFrame(frame);Object.assign(window,{render_game_to_text:()=>JSON.stringify(game.snapshot())});
 }catch(err){console.error(err);$('loading').innerHTML='<h2>The crew could not start.</h2><p>Check your connection and browser graphics support, then refresh.</p><button onclick="location.reload()">Try again</button>';}}
void boot();
